In [1]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("../data/Titanic-Dataset.csv")
p = pd.read_csv("../data/Planets.csv")
tip = pd.read_csv("../data/tip.csv")

In [3]:
print(df.shape, p.shape)

(891, 12) (1035, 6)

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.loc[df.groupby('Pclass')['Age'].idxmax(),['Pclass','Name','Fare','Age']]

     Pclass                                  Name    Fare   Age
630       1  Barkworth, Mr. Algernon Henry Wilson  30.000  80.0
672       2           Mitchell, Mr. Henry Michael  10.500  70.0
851       3                   Svensson, Mr. Johan   7.775  74.0

In [13]:
tip.groupby("day").size()

day
Fri     19
Sat     87
Sun     76
Thur    62
dtype: int64

In [16]:
tip.groupby("day")['tip'].mean().round(2)

day
Fri     2.73
Sat     2.99
Sun     3.26
Thur    2.77
Name: tip, dtype: float64